/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAboutRouteImport } from './routes/_auth/about'
import { Route as AuthTransactionIndexRouteImport } from './routes/_auth/transaction/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthCategoryIndexRouteImport } from './routes/_auth/category/index'
import { Route as AuthBudgetIndexRouteImport } from './routes/_auth/budget/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAboutRoute = AuthAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionIndexRoute = AuthTransactionIndexRouteImport.update({
  id: '/transaction/',
  path: '/transaction/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCategoryIndexRoute = AuthCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBudgetIndexRoute = AuthBudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/about': typeof AuthAboutRoute
  '/budget/': typeof AuthBudgetIndexRoute
  '/category/': typeof AuthCategoryIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/transaction/': typeof AuthTransactionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/about': typeof AuthAboutRoute
  '/budget': typeof AuthBudgetIndexRoute
  '/category': typeof AuthCategoryIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/transaction': typeof AuthTransactionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_auth/about': typeof AuthAboutRoute
  '/_auth/budget/': typeof AuthBudgetIndexRoute
  '/_auth/category/': typeof AuthCategoryIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/transaction/': typeof AuthTransactionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/about'
    | '/budget/'
    | '/category/'
    | '/dashboard/'
    | '/transaction/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/about'
    | '/budget'
    | '/category'
    | '/dashboard'
    | '/transaction'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/logout'
    | '/_auth/about'
    | '/_auth/budget/'
    | '/_auth/category/'
    | '/_auth/dashboard/'
    | '/_auth/transaction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/about': {
      id: '/_auth/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transaction/': {
      id: '/_auth/transaction/'
      path: '/transaction'
      fullPath: '/transaction/'
      preLoaderRoute: typeof AuthTransactionIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/category/': {
      id: '/_auth/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof AuthCategoryIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/budget/': {
      id: '/_auth/budget/'
      path: '/budget'
      fullPath: '/budget/'
      preLoaderRoute: typeof AuthBudgetIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAboutRoute: typeof AuthAboutRoute
  AuthBudgetIndexRoute: typeof AuthBudgetIndexRoute
  AuthCategoryIndexRoute: typeof AuthCategoryIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthTransactionIndexRoute: typeof AuthTransactionIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAboutRoute: AuthAboutRoute,
  AuthBudgetIndexRoute: AuthBudgetIndexRoute,
  AuthCategoryIndexRoute: AuthCategoryIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthTransactionIndexRoute: AuthTransactionIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
